          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx
          configMap:
            name: nginx-configmap
      {{- with .Values.nodeSelector }}